---
experiment_desc: XYScanNet_stage2

train:
  files_a: /scratch/user/hanzhou1996/datasets/deblur/RealBlur_R/train/trainA/*.png
  files_b: /scratch/user/hanzhou1996/datasets/deblur/RealBlur_R/train/trainB/*.png
  size: &SIZE 320
  crop: random
  preload: &PRELOAD false
  preload_size: &PRELOAD_SIZE 0
  bounds: [0, 1]
  scope: geometric

val:
  files_a: /scratch/user/hanzhou1996/datasets/deblur/RealBlur_R/test/testA/*.png
  files_b: /scratch/user/hanzhou1996/datasets/deblur/RealBlur_R/test/testB/*.png
  size: *SIZE
  scope: None
  crop: random
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  bounds: [0, 1]

model:
  g_name: XYScanNetP
  content_loss: Stripformer_Loss

num_epochs: 2000
train_batches_per_epoch: 3758
val_batches_per_epoch: 980
batch_size: 8
image_size: [320, 320]

optimizer:
  name: adam
  lr: 0.0001
scheduler:
  name: cosine
  start_epoch: 50
  min_lr: 0.0000001